artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Hochunseng/steam-review-generator/raw/main/data/battlebit-remastered-reviews.zip
  local_data_file: artifacts/data_ingestion/battlebit-remastered-reviews.zip
  unzip_dir: artifacts/data_ingestion